apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::363587345741:role/UdacityFlaskDeployCBKubectlRole
    username: build
    groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-02-13T00:06:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "873"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a6887db0-4df4-11ea-adf2-0a0cda35eb20
